default:
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1

stages:
  - build
  - deploy

build-image:
  stage: build
  tags: [docker]
  script:
    - docker build -t yt-bot:$CI_COMMIT_SHA .
    - docker save my-yt-bot:$CI_COMMIT_SHA > image.tar
  artifacts:
    paths: [image.tar]
    expire_in: 1 hour